# Pairwise distances

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv('taxi.csv', index_col = 'Unnamed: 0')
df.head()

count(1)  month    year  dayofweek  hour  pickup_community_area
0      2742   11.0  2014.0        7.0  21.0                   32.0
1       200   11.0  2014.0        6.0  23.0                   77.0
2       110    4.0  2014.0        7.0  19.0                   16.0
3      3205   12.0  2016.0        4.0  16.0                    8.0
4      1159   12.0  2014.0        7.0  22.0                   24.0

In [3]:
df.shape

(479360, 6)

In [4]:
df= df.drop(["month", "year", "dayofweek"], axis=1)
df.rename(columns={'count(1)':'count'}, inplace=True)
df.head()

count  hour  pickup_community_area
0   2742  21.0                   32.0
1    200  23.0                   77.0
2    110  19.0                   16.0
3   3205  16.0                    8.0
4   1159  22.0                   24.0

In [5]:
df2 = pd.read_csv('destination_demand.csv', index_col = 'Unnamed: 0')
df2.head()

count(1)  month    year  dayofweek  hour  dropoff_community_area
0      4939    2.0  2013.0        1.0   0.0                     8.0
1      2655    2.0  2013.0        5.0  14.0                     8.0
2       672    5.0  2014.0        1.0   8.0                    33.0
3      1657    7.0  2016.0        4.0  19.0                    28.0
4      1838    3.0  2013.0        7.0  18.0                    28.0

# pickup calculation

In [16]:
Y = np.array(df['count'])
Y

array([2742,  200,  110, ...,    1,    1,    1])

In [17]:
X = np.array(df['pickup_community_area'])
X

array([32., 77., 16., ..., 20., 46., 40.])

In [18]:
st=np.column_stack((X,Y))
st

array([[3.200e+01, 2.742e+03],
       [7.700e+01, 2.000e+02],
       [1.600e+01, 1.100e+02],
       ...,
       [2.000e+01, 1.000e+00],
       [4.600e+01, 1.000e+00],
       [4.000e+01, 1.000e+00]])

In [19]:
st.ndim

2

In [20]:
from sklearn.metrics.pairwise import pairwise_distances
pairwise_distances(X,Y)

ValueError: Expected 2D array, got 1D array instead:
array=[32. 77. 16. ... 20. 46. 40.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

# dropoff calculation